baseURL = 'https://www.charlottehunter.ca/'
languageCode = 'en'
title = 'Charlotte Hunter'
author = 'Charlotte Hunter'
theme = "hugo-paper-main"

[deployment]
  order = [".jpg", ".png", ".webp", ".gif", ".svg"]

[params]
  color = 'wheat'
  twitter = 'kijekijikokwe'
  github = 'kijekijikokwe'
  avatar = 'me@charlottehunter.ca'
  name = 'Char'
  bio = 'Métis Two-Spirit Social Justice Warrior'
  description = "Professional website of Charlotte Hunter"
  homeSubtitle = 'Métis Two-Spirit Social Justice Warrior'
  customCSS = ["css/custom.css"]

  [params.giscus]
    repo = "kijekijikokwe/kijekijikokwe.github.io"
    repoId = "R_kgDOP8wdYA"
    category = "General"
    categoryId = "DIC_kwDOP8wdYM4C3N8C"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "gruvbox_light"
    lang = "en"

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "Resume & CV"
    url = "/cv/"
    weight = 1
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2
